### ISSUE TITLE
GitHub Actions for Jest coverage fails with error

### ISSUE THREAD

**Issue by ttsukagoshi** [ttsukagoshi/csv2gsheets#180]
```shell
Error: The process '/usr/local/bin/npm' failed with exit code 1
Error: The process '/usr/local/bin/npm' failed with exit code 1
    at wd._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:19186)
    at wd.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:18773)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:21:17765)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
```

**Comment by ttsukagoshi** [comment]
Fixed in #181
